title_name = "Gears of War 2" # TU6
title_id = "4D53082D" # MS-2093
hash = "62547A005C0420D2" # default.xex
#media_id = "33FCE762"

[[patch]]
    name = "Unlock FPS"
    desc = "Framerates higher than 60 FPS require vsync to be changed from true to false in the Xenia config."
    author = "illusion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x824a2fa4
        value = 0x60000000
    [[patch.be8]]
        address = 0x829a6f53
        value = 0x01

[[patch]]
    name = "Black Shading Fix"
    desc = "Modifies how dynamic shadows are cast from spherical harmonic lighting. Most of the shadowing artifacts are mediated but there are still some terrain shadows and character self-shadowing that won't look good."
    author = "illusion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822e96d8
        value = 0x39600000

[[patch]]
    name = "RTV - Flickering Decals Fix"
    desc = "Disables static decals that cause z-fighting with RTV rendering. Some visual artifacts may remain. Not necessary when using ROV."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822d6f04
        value = 0x39200000

[[patch]]
    name = "Disable Ambient Occlusion"
    desc = "Fixes various artifacts when using upscaling."
    author = "illusion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82700198
        value = 0x39600000

[[patch]]
    name = "Disable Motion Blur"
    desc = "Solves most ghosting and artifacting caused by quickly panning cameras."
    author = "illusion, boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8237186c
        value = 0x39600000

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8281e3b4
        value = 0x38a00010

[[patch]]
    name = "Disable Lens Flares"
    desc = "Fixes unoccluded bright lights on-screen."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x827be894
        value = 0x39400000

[[patch]]
    name = "Disable Depth of Field"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822e3910
        value = 0x39600000
    [[patch.be32]]
        address = 0x82422768
        value = 0x39600000
    [[patch.be32]]
        address = 0x824f2234
        value = 0x39200000
    [[patch.be32]]
        address = 0x824f2374
        value = 0x39600000

[[patch]]
    name = "Disable Bloom"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822e3904
        value = 0x39400000
    [[patch.be32]]
        address = 0x824f2240
        value = 0x39400000
    [[patch.be32]]
        address = 0x824f2380
        value = 0x39600000
