title_name = "Rockstar Games Presents Table Tennis"
title_id = "545407DF" # TT-2015
hash = "5FDE016D496FD6C1" # default.xex
#media_id = [
#    "434C4803", # Disc, (USA, Europe): http://redump.org/disc/23954
#    "6D0AB0E0", # XBLA: c6656ecd4d65a0405fd82cb71b04560ef1e848b1
#]

[[patch]]
    name = "Crash Fix"
    desc = "Bypasses guest crash error during boot. Disables light shafts which require access to 0xCDCDCDCD memory range, resulting in visual quality that's slightly different to native console."
    author = "Gliniak, boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x8237a3c4
        value = 0x4800
    [[patch.be16]]
        address = 0x8237992c
        value = 0x4800
    [[patch.be32]]
        address = 0x82307db8
        value = 0x39600000
    [[patch.be32]]
        address = 0x82308270
        value = 0x38600000
